name: .NET Core CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.gitignore'
      - '**.dockerignore'
      - '**/README.md'
      - '**/stylecop.props'
      - '**/stylecop.ruleset'
      - '**/stylecop.json'
      - '**/common.props'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.gitignore'
      - '**.dockerignore'
      - '**/README.md'
      - '**/stylecop.props'
      - '**/stylecop.ruleset'
      - '**/stylecop.json'
      - '**/common.props'
jobs:
  build:
    runs-on: ${{ matrix.os }} 
    defaults:
      run:
        shell: bash
        working-directory: ./myHouse
    strategy:
      matrix: 
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal
