name: Node CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
  # Triggers the workflow on push or pull request events but only for the main branch
    branches: [ main ]
    paths-ignore:
      - '**.gitignore'
      - '**/README.md'
      - '**.dockerignore'
      
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.gitignore'
      - '**/README.md'
      - '**.dockerignore'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./myHouse.Client
    strategy:
      matrix: 
        os: [ubuntu-20.04, windows-2019, macos-11]
        node-version: [16.x, 15.x, 14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build --if-present

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
